// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYgOdl-Xis0SI_1PjfoIUkZoHdVcUPC2g',
    appId: '1:77556485294:web:e711db054894fc1190313f',
    messagingSenderId: '77556485294',
    projectId: 'snova-9a86d',
    authDomain: 'snova-9a86d.firebaseapp.com',
    storageBucket: 'snova-9a86d.firebasestorage.app',
    measurementId: 'G-W9H8XPZY57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLPfc1t9dKzttWnxwHCCIcE0rQfbpUC9o',
    appId: '1:77556485294:android:bed5e44aa6e5f4b690313f',
    messagingSenderId: '77556485294',
    projectId: 'snova-9a86d',
    storageBucket: 'snova-9a86d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9bEfCUrHtpxm1y6btrWvd5MQgw5Ynuk0',
    appId: '1:77556485294:ios:75c359c9d6accade90313f',
    messagingSenderId: '77556485294',
    projectId: 'snova-9a86d',
    storageBucket: 'snova-9a86d.firebasestorage.app',
    androidClientId: '77556485294-a0mean3ns5l04vcm0l529b1e0p7k8h4o.apps.googleusercontent.com',
    iosClientId: '77556485294-o5jabhmrvv34i1oud1d2q8g7qj741nkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.snova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9bEfCUrHtpxm1y6btrWvd5MQgw5Ynuk0',
    appId: '1:77556485294:ios:75c359c9d6accade90313f',
    messagingSenderId: '77556485294',
    projectId: 'snova-9a86d',
    storageBucket: 'snova-9a86d.firebasestorage.app',
    androidClientId: '77556485294-a0mean3ns5l04vcm0l529b1e0p7k8h4o.apps.googleusercontent.com',
    iosClientId: '77556485294-o5jabhmrvv34i1oud1d2q8g7qj741nkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.snova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYgOdl-Xis0SI_1PjfoIUkZoHdVcUPC2g',
    appId: '1:77556485294:web:b4c60f1d44ba20de90313f',
    messagingSenderId: '77556485294',
    projectId: 'snova-9a86d',
    authDomain: 'snova-9a86d.firebaseapp.com',
    storageBucket: 'snova-9a86d.firebasestorage.app',
    measurementId: 'G-JZYG1E91KV',
  );
}
